// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aa.aa.domain;

import com.aa.aa.domain.Delivery;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Delivery_Roo_Configurable {
    
    declare @type: Delivery: @Configurable;
    
}
