// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aa.aa.domain;

import com.aa.aa.domain.Hi;

privileged aspect Hi_Roo_JavaBean {
    
    public String Hi.getName() {
        return this.name;
    }
    
    public void Hi.setName(String name) {
        this.name = name;
    }
    
}
